API_URL: http://127.0.0.1:8080
instruction: You are an AI assistant. User will you give you a task. Your goal is to complete the task as faithfully as you can.
inference:
  temperature: 0.7
  top_k: 40
  top_p: 0.95
  n_predict: 512
  cache_prompt: true
  slot_id: -1
  stream: true
convo:
  User_name: User
  Bot_name: Assistant
  hack_prompt: "Here is the topic and the question answer pairs separated by a dash like you specified.\nTopic:"
prompt:
  text_first: true
