printWidth: 110
bracketSameLine: true
semi: false
singleQuote: false
svelteSortOrder: scripts-options-markup-styles
svelteStrictMode: false
plugins:
  - prettier-plugin-svelte
overrides:
  - files: "*.svelte"
    options:
      parser: "svelte"

