using WebAssemblyCompiler
cd(@__DIR__)

peccatoribus(x::Float64) = 2x
funs = ((peccatoribus, Float64))
compile(funs; filepath="../supabase-sveltekit/static/main.wasm", validate=true, optimize=false)


# const h = JS.h

# function basics(x)
#     n = h("p",
#         h("strong", " This is strong text with a class."), class="myclass")
#     n = h("div", "This is some text generated by `JS.h`. ",
#         "This is a number: ", x, n, class="myclass2")
#     JS.sethtml("myid", string(n))
#     ## JS.eval("alert('Generated by Julia')")  # It works, but it's too annoying.
#     JS.console_log((arr=[1.0, 2.0, 3.0], str="hello", num=2.0, tp=(3, 3.0)))
#     return x
# end
# nothing #hide

# # Compile it using:

# compile((basics, Float64); filepath="../supabase-sveltekit/static/basics.wasm", validate=true, optimize=false)
